---
services:
  yard-sale-api:
    restart: always
    build:
      dockerfile: ./apps/yard-sale-api/Dockerfile
      context: .
    ports:
      - 3000:3000
    volumes:
      - yard-sale-api-node_modules:/app/node_modules
  yard-sale-app:
    restart: always
    build:
      dockerfile: ./apps/yard-sale-app/Dockerfile
      context: .
    ports:
      - 4200:4200
    volumes:
      - yard-sale-app-node_modules:/app/node_modules

volumes:
  yard-sale-api-node_modules:
  yard-sale-app-node_modules:
